heroku:
  stage: deploy
  only:
    - master
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/sea-store-backend-users.git
    - git add .
    - git commit -m 'Deploying to Heroku'
    - git push -f heroku master