logging.level.org.springframework: debug

spring:
  devtools:
    restart:
      additional-paths: /src

server:
  port: 3000

app:
  datasource:
    jdbc-url: ${DATABASE_JDBC_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool-size: 30
